#!/usr/bin/env bash
# =============================================================================
# build_wp.sh — build Born_on_Schedule.pdf, the WORKING-PAPER edition: one file
# containing the paper, Appendices A (model) and B (data), and the Supplementary
# Appendix (C, D, E).
#
# Born_on_Schedule.tex is GENERATED from paper.tex on every run; never edit it by
# hand. Edit paper.tex / appendix.tex / sup_appendix.tex and re-run this script.
#
# What the generation does:
#   * takes paper.tex's preamble verbatim, minus \usepackage{xr} and
#     \externaldocument{supplement} (the supplement is internal here, so the
#     external cross-reference machinery would only duplicate labels);
#   * redefines \satab / \safig as plain Table~\ref / Figure~\ref;
#   * takes the body through \input{appendix} (Appendices A and B), then adds a
#     banner and \input{sup_appendix}, whose sections continue the counter as
#     C, D and E on their own;
#   * one bibliography serves the whole document.
#
# Usage:  cd latex && ./build_wp.sh
# =============================================================================
set -euo pipefail
cd "$(dirname "$0")"

SRC=paper.tex
OUT=Born_on_Schedule

grep -q '^\\input{appendix}' "$SRC" || { echo "build_wp.sh: no \\input{appendix} in $SRC"; exit 1; }

{
  echo "% GENERATED by build_wp.sh from paper.tex — do not edit by hand."
  # preamble, up to but excluding \begin{document}
  sed -n '1,/^\\begin{document}$/p' "$SRC" | sed '$d' \
    | grep -v '^\\usepackage{xr}' \
    | grep -v '^\\externaldocument' \
    | sed 's|^\\newcommand{\\satab}.*|\\newcommand{\\satab}[1]{Table~\\ref{#1}}|' \
    | sed 's|^\\newcommand{\\safig}.*|\\newcommand{\\safig}[1]{Figure~\\ref{#1}}|'
  # body, from \begin{document} through \input{appendix} (Appendices A and B)
  sed -n '/^\\begin{document}$/,/^\\input{appendix}/p' "$SRC"
  # the supplement, as Appendices C, D and E of the same document
  cat <<'TEX'

\clearpage
\phantomsection
\addcontentsline{toc}{section}{Supplementary Appendix}
\begin{center}{\Large\bfseries Supplementary Appendix}\end{center}
\vspace{0.5em}

\input{sup_appendix}

\end{document}
TEX
} > "$OUT.tex"

pdflatex -interaction=nonstopmode "$OUT" >/dev/null
bibtex "$OUT" >/dev/null
pdflatex -interaction=nonstopmode "$OUT" >/dev/null
pdflatex -interaction=nonstopmode "$OUT" >/dev/null

echo "$OUT.pdf: $(pdfinfo $OUT.pdf | awk '/^Pages/{print $2}') pages"
echo "undefined references: $(grep -c 'Reference .* undefined' $OUT.log || true)"
echo "undefined citations:  $(grep -c 'Citation .* undefined' $OUT.log || true)"
