#!/usr/bin/env bash
# =============================================================================
# build_wp.sh — build Born_on_Schedule.pdf, the WORKING-PAPER edition: one file
# containing the paper, Appendices A (model) and B (data), and the Supplementary
# Appendix (C, D, E).
#
# Born_on_Schedule.tex is GENERATED from paper.tex on every run; never edit it by
# hand. Edit paper.tex / appendix.tex / sup_appendix.tex and re-run this script.
#
# What the generation does:
#   * takes paper.tex's preamble verbatim, minus \usepackage{xr} and
#     \externaldocument{supplement} (the supplement is internal here, so the
#     external cross-reference machinery would only duplicate labels);
#   * applies the two WP-ONLY edits listed under WP_EDITS below: a dated title
#     page, and a data-availability sentence that does not address editors and
#     referees, who do not exist for a working paper. paper.tex, the version
#     submitted to the journal, keeps neither. Both are guarded: if a future edit
#     to paper.tex moves the text they match, this script FAILS instead of
#     silently producing a WP without them;
#   * redefines \satab / \safig as plain Table~\ref / Figure~\ref;
#   * takes the body through \input{appendix} (Appendices A and B), then adds a
#     banner and \input{sup_appendix}, whose sections continue the counter as
#     C, D and E on their own;
#   * one bibliography serves the whole document.
#
# Usage:  cd latex && ./build_wp.sh
# =============================================================================
set -euo pipefail
cd "$(dirname "$0")"

SRC=paper.tex
OUT=Born_on_Schedule

grep -q '^\\input{appendix}' "$SRC" || { echo "build_wp.sh: no \\input{appendix} in $SRC"; exit 1; }

{
  echo "% GENERATED by build_wp.sh from paper.tex — do not edit by hand."
  # preamble, up to but excluding \begin{document}
  sed -n '1,/^\\begin{document}$/p' "$SRC" | sed '$d' \
    | grep -v '^\\usepackage{xr}' \
    | grep -v '^\\externaldocument' \
    | sed 's|^\\newcommand{\\satab}.*|\\newcommand{\\satab}[1]{Table~\\ref{#1}}|' \
    | sed 's|^\\newcommand{\\safig}.*|\\newcommand{\\safig}[1]{Figure~\\ref{#1}}|'
  # body, from \begin{document} through \input{appendix} (Appendices A and B)
  sed -n '/^\\begin{document}$/,/^\\input{appendix}/p' "$SRC"
  # the supplement, as Appendices C, D and E of the same document
  cat <<'TEX'

\clearpage
\phantomsection
\addcontentsline{toc}{section}{Supplementary Appendix}
\begin{center}{\Large\bfseries Supplementary Appendix}\end{center}
\vspace{0.5em}

\input{sup_appendix}

\end{document}
TEX
} > "$OUT.tex"

# --- WP_EDITS: the two differences between the working paper and the submission
# 1. a dated title page (the journal version carries no date)
# 2. a data-availability sentence addressed to readers, not to editors and referees
export WP_VERSION="${WP_VERSION:-September 2026}"
perl -0777 -i -pe '
  BEGIN { $v = $ENV{WP_VERSION} }
  $n = 0;
  $n += s/^\\date\{\}$/\\date{This version: $v}/m;
  $n += s/A draft replication package is available to editors and referees and will be\n(deposited in a trusted open repository prior to acceptance\.)/A draft replication package is available from the corresponding author on\nrequest and will be $1/;
  die "build_wp.sh: WP_VERSION is empty\n" unless length $v;
  die "build_wp.sh: WP_EDITS matched $n of 2 patterns; paper.tex has moved the text they anchor on\n" unless $n == 2;
' "$OUT.tex"

pdflatex -interaction=nonstopmode "$OUT" >/dev/null
bibtex "$OUT" >/dev/null
pdflatex -interaction=nonstopmode "$OUT" >/dev/null
pdflatex -interaction=nonstopmode "$OUT" >/dev/null

echo "$OUT.pdf: $(pdfinfo $OUT.pdf | awk '/^Pages/{print $2}') pages"
echo "undefined references: $(grep -c 'Reference .* undefined' $OUT.log || true)"
echo "undefined citations:  $(grep -c 'Citation .* undefined' $OUT.log || true)"
